services:
  - type: web
    name: portfolio  # ← tu peux corriger aussi le nom ici
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        value: 3#$vu-xtueiep+7+wh(ex6ass5ea*0ly%0*h@wy+rr7jk@cyni
      - key: DEBUG
        value: false
