services:
  - type: web
    name: portofolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portofolio.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portofolio.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
