# Generated by Django 5.2.3 on 2025-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='mon_cv', max_length=255)),
                ('fichier', models.FileField(upload_to='media/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
